main_font_list = [
    "Segoe UI",
    "Inter",
    "Open Sans",
    "Arial",
    "Courier New",
    "Times New Roman",
    "Verdana",
    "Consolas",
    "Georgia",
    "Calibri",
    "Tahoma",
    "TrebuchetMS",
    "Helvetica",
]